const level_1 = new Level(
    level_end_x = 4000,
    backgroundObjects = [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 6)
    ],
    clouds = [
        new Cloud('img/5_background/layers/4_clouds/1.png', 0),
        new Cloud('img/5_background/layers/4_clouds/2.png', 720),
        new Cloud('img/5_background/layers/4_clouds/1.png', 720 * 2),
        new Cloud('img/5_background/layers/4_clouds/2.png', 720 * 3),
        new Cloud('img/5_background/layers/4_clouds/2.png', 720 * 4),
        new Cloud('img/5_background/layers/4_clouds/1.png', 720 * 5)
    ],
    enemies = [
        // new SmallChicken(this.level_end_x),
        // new SmallChicken(this.level_end_x),
        // new SmallChicken(this.level_end_x),
        // new SmallChicken(this.level_end_x),
        // new SmallChicken(this.level_end_x),
        // new Chicken(this.level_end_x),
        // new Chicken(this.level_end_x),
        // new Chicken(this.level_end_x),
        // new Chicken(this.level_end_x),
        // new Chicken(this.level_end_x),
        // new Endboss()
    ],
    bottles = [
        new CollectableBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png'),
        new CollectableBottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png'),
        new CollectableBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png'),
        new CollectableBottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png'),
        new CollectableBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png')
    ],
    coins = [
        new CollectableCoin(800, 150),
        new CollectableCoin(1300, 150),
        new CollectableCoin(1900 - 120, 75 + 125),
        new CollectableCoin(1900 - 100, 75 + 75),
        new CollectableCoin(1900 - 60, 75 + 25),
        new CollectableCoin(1900, 75),
        new CollectableCoin(1900 + 60, 75 + 25),
        new CollectableCoin(1900 + 100, 75 + 75),
        new CollectableCoin(1900 + 120, 75 + 125),
        new CollectableCoin(2400, 150)
    ]

);